import type { Metadata } from "next";

import "./globals.css";
import { UiProvider } from "./ui-provider";
import { WindowDecoration } from "./components/native/window-decoration";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" !bg-transparent border border-solid h-[100vh]">
        <UiProvider>
          <WindowDecoration />
          {children}
        </UiProvider>
      </body>
    </html>
  );
}
